import { Link } from 'react-router-dom';
import { useState } from 'react';
import type { Order, OperatorOverview, PizzaItem } from '@guigs/shared';
import { ovenQueues } from '../features/oven/oven';
import { finishingProgress } from '../features/finishing/finishing';
import { operatorLoads, orderProgress, overviewCounts, stageLabel, pizzas } from '../features/kitchen/overview';
import { useKitchenOverview } from '../features/kitchen/useKitchenOverview';
import './kitchen-overview.css';

type Filter = 'ALL' | 'ASSEMBLY' | 'OVEN' | 'FINISHING' | 'DISPATCH';
const statusLabels: Record<Order['status'], string> = { WAITING_PRODUCTION: 'Aguardando produção', IN_PRODUCTION: 'Em produção', OVEN: 'Forno', FINISHING: 'Finalização', WAITING_DISPATCH: 'Aguardando despacho', WAITING_DRIVER: 'Aguardando motoboy', OUT_FOR_DELIVERY: 'Em rota', DELIVERED: 'Entregue', READY_FOR_PICKUP: 'Pronto para retirada', PICKED_UP: 'Retirado', CANCELLED: 'Cancelado' };
const connectionLabels = { ONLINE: 'Online', RECONNECTING: 'Reconectando', OFFLINE: 'Offline' } as const;
const time = (value?: string | null) => value ? new Date(value).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }) : '—';
function stageMatches(order: Order, filter: Filter) { if (filter === 'ALL') return true; const states = pizzas([order]).map(p => p.production.state); if (filter === 'ASSEMBLY') return states.some(s => ['WAITING_ASSEMBLY', 'ASSEMBLING', 'ASSEMBLY_PAUSED'].includes(s)); if (filter === 'OVEN') return states.some(s => ['WAITING_OVEN', 'IN_OVEN'].includes(s)); if (filter === 'FINISHING') return order.status === 'FINISHING' || states.some(s => ['BAKED', 'FINISHING'].includes(s)); return ['WAITING_DISPATCH', 'WAITING_DRIVER', 'OUT_FOR_DELIVERY', 'READY_FOR_PICKUP'].includes(order.status); }
function OperatorCard({ operator, load }: { operator: OperatorOverview; load: { waiting: number; active: number; total: number } }) { return <article className="ko-operator"><div><strong>{operator.operatorName}</strong><span>{operator.workstationName ?? 'Sem terminal ativo'}</span></div><span className={`ko-presence ko-${operator.presenceStatus.toLowerCase()}`}>{operator.presenceStatus === 'ONLINE' ? 'Online' : operator.presenceStatus === 'STALE' ? 'Atenção' : 'Offline'}</span><b>{load.total} {load.total === 1 ? 'pizza' : 'pizzas'}</b><small>{load.active} em montagem · {load.waiting} aguardando</small></article>; }
function PizzaLine({ pizza }: { pizza: PizzaItem }) { return <li><span>Pizza {pizza.position + 1}</span><strong>{pizza.snapshot.size === 'BROTO' ? 'Broto' : 'Grande'} · {pizza.snapshot.composition === 'HALF_HALF' ? 'Meio a meio' : 'Inteira'}</strong><em>{stageLabel(pizza.production.state)}</em><small>{pizza.assignment?.operatorName ? `Responsável: ${pizza.assignment.operatorName}` : `Enfileirada às ${time(pizza.production.queuedAt)}`}</small></li>; }
function OrderCard({ order }: { order: Order }) { const progress = orderProgress(order); return <article className="ko-order"><header><div><strong>#{String(order.number).padStart(4, '0')}</strong><h3>{order.customerName}</h3><span>{order.fulfillmentType === 'DELIVERY' ? 'Delivery' : order.fulfillmentType === 'PICKUP' ? 'Retirada' : 'Balcão'} · recebido às {time(order.receivedAt)}</span></div><span className="ko-order-status">{statusLabels[order.status]}</span></header><div className="ko-progress"><b>{progress.label}</b><span>{order.items.length} itens · {progress.assembly ? `${progress.assembly} em montagem` : progress.inOven ? `${progress.inOven} no forno` : 'fluxo avançado'}</span></div><details><summary>Ver pizzas e detalhes</summary><ul className="ko-pizzas">{order.items.filter((item): item is PizzaItem => item.kind === 'PIZZA').map(pizza => <PizzaLine key={pizza.id} pizza={pizza} />)}</ul>{order.notes && <p className="ko-note">Observação: {order.notes}</p>}</details></article>; }

export function Kitchen() {
  const { orders, operators, loading, refreshing, error, connection, refresh } = useKitchenOverview(); const [filter, setFilter] = useState<Filter>('ALL'); const counts = overviewCounts(orders); const loads = operatorLoads(orders); const oven = ovenQueues(orders); const finishing = orders.filter(order => order.status === 'FINISHING'); const dispatch = orders.filter(order => ['WAITING_DISPATCH', 'WAITING_DRIVER', 'OUT_FOR_DELIVERY', 'READY_FOR_PICKUP'].includes(order.status)); const visible = orders.filter(order => stageMatches(order, filter));
  return <section className="page kitchen-overview"><header className="ko-head"><div><div className="eyebrow">SUPERVISÃO · COZINHA</div><h1>Central Operacional da Cozinha</h1><p>Acompanhamento compartilhado das filas persistidas, sem executar comandos.</p></div><div className="ko-head-actions"><span role="status" className={`ko-connection ko-${connection.toLowerCase()}`}>{connectionLabels[connection]}</span><button className="button secondary" type="button" disabled={refreshing} onClick={() => void refresh()}>{refreshing ? 'Atualizando…' : 'Atualizar'}</button></div></header>
    <nav className="ko-links" aria-label="Módulos operacionais"><Link className="button subtle" to="/kitchen/assembly">Montagem</Link><Link className="button subtle" to="/kitchen/oven">Forno</Link><Link className="button subtle" to="/kitchen/finishing">Finalização</Link><Link className="button subtle" to="/kitchen/dispatch">Despacho</Link></nav>
    {error && <p className="alert" role="alert">{error} <button type="button" onClick={() => void refresh()}>Tentar novamente</button></p>}
    <section className="ko-metrics" aria-label="Resumo da produção">{[['Aguardando montagem', counts.waitingAssembly], ['Em montagem', counts.assembling], ['Aguardando forno', counts.waitingOven], ['No forno', counts.inOven], ['Finalização', counts.finishing], ['Aguardando despacho', counts.waitingDispatch]].map(([label, value]) => <div className="ko-metric" key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <div className="ko-filter" role="group" aria-label="Filtro da central">{(['ALL', 'ASSEMBLY', 'OVEN', 'FINISHING', 'DISPATCH'] as Filter[]).map(value => <button key={value} type="button" className="button subtle" aria-pressed={filter === value} onClick={() => setFilter(value)}>{({ ALL: 'Todos', ASSEMBLY: 'Montagem', OVEN: 'Forno', FINISHING: 'Finalização', DISPATCH: 'Despacho' })[value]}</button>)}</div>
    <div className="ko-grid"><section className="ko-panel"><div className="ko-panel-head"><h2>Operadores e carga</h2><span>{operators.length} ativos cadastrados</span></div>{operators.length ? <div className="ko-operators">{operators.map(operator => <OperatorCard key={operator.operatorId} operator={operator} load={loads.get(operator.operatorId) ?? { waiting: 0, active: 0, total: 0 }} />)}</div> : <p className="ko-empty">Nenhuma sessão operacional disponível no momento.</p>}</section><section className="ko-panel"><div className="ko-panel-head"><h2>Forno</h2><span>{oven.inside.length} dentro · {oven.waiting.length} aguardando</span></div><p className="ko-summary">A fila e os timers são os mesmos exibidos no módulo de forno. A Central apenas acompanha.</p>{!oven.inside.length && !oven.waiting.length && <p className="ko-empty">Nenhuma pizza nas filas do forno.</p>}{oven.inside.length > 0 && <p className="ko-stage">{oven.inside.length} pizza(s) em produção no forno</p>}{oven.waiting.length > 0 && <p className="ko-stage">{oven.waiting.length} pizza(s) aguardando entrada</p>}</section><section className="ko-panel"><div className="ko-panel-head"><h2>Finalização</h2><span>{finishing.length} pedido(s)</span></div>{finishing.length ? finishing.map(order => { const progress = finishingProgress(order); return <p className="ko-stage" key={order.id}>#{order.number}: {progress.checked}/{progress.total} itens conferidos</p>; }) : <p className="ko-empty">Nenhum pedido em finalização.</p>}</section><section className="ko-panel"><div className="ko-panel-head"><h2>Despacho</h2><span>{dispatch.length} pedido(s)</span></div>{dispatch.length ? dispatch.map(order => <p className="ko-stage" key={order.id}>#{order.number}: {statusLabels[order.status]}</p>) : <p className="ko-empty">Nenhum pedido aguardando despacho.</p>}</section></div>
    <section className="ko-panel ko-orders"><div className="ko-panel-head"><h2>Pedidos consolidados</h2><span>{visible.length} de {orders.length}</span></div>{loading && <p role="status" className="ko-empty">Carregando pedidos persistidos…</p>}{!loading && !visible.length && <p className="ko-empty">Nenhum pedido neste filtro.</p>}<div className="ko-order-list">{visible.map(order => <OrderCard key={order.id} order={order} />)}</div></section>
  </section>;
}
