import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useOperatorSession } from './useOperatorSession';
import { OperatorPin } from './components/OperatorPin';
import { AssemblyIcon } from './components/AssemblyIcons';
import { useOperationalFlow } from './useOperationalFlow';
import { RouteStaging } from './RouteStaging';
import { ovenQueues, ovenFlavor, ovenTiming, elapsedSeconds, formatDuration } from '../oven/oven';
import type { OperationalSession } from '@guigs/shared';
import type { SessionCredentials } from './operatorSession';
import './assembly.css';
import '../oven/oven.css';
import '../finishing/finishing.css';
import './operational-flow.css';

export function ProductionStation() { const auth = useOperatorSession(); if (!auth.session || !auth.credentials) return <OperatorPin {...auth} module="Forno e Finalização" />; return <Station key={auth.session.sessionId} session={auth.session} credentials={auth.credentials} authBusy={auth.busy} authError={auth.error} end={auth.end} setAvailability={auth.setAvailability} />; }
function Station({ session, credentials, authBusy, authError, end, setAvailability }: { session: OperationalSession; credentials: SessionCredentials; authBusy: boolean; authError: string; end: () => Promise<void>; setAvailability: (value: boolean) => Promise<void> }) {
  const queue = useOperationalFlow(credentials, session.sessionId), [now, setNow] = useState(Date.now()); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const serverNow = now + (queue.config?.offset ?? 0), oven = ovenQueues(queue.orders), finishing = queue.orders.flatMap(order => order.items.flatMap(pizza => pizza.kind === 'PIZZA' && ['BAKED', 'FINISHING'].includes(pizza.production.state) ? [{ order, pizza }] : []));
  const enabled = queue.canAct && !authBusy && !authError && session.presenceStatus === 'ONLINE';
  return <section className="oven-page production-station"><header className="oven-header"><div><h1><AssemblyIcon name="oven" />Forno e Finalização</h1><p aria-label="Identidade operacional">{session.operatorName} · {session.workstationName}</p></div><div className="oven-header-actions"><span role="status" aria-label="Conexão Forno e Finalização">{queue.connection === 'ONLINE' ? 'Online' : queue.connection === 'OFFLINE' ? 'Offline' : 'Reconectando'}</span><Link className="button subtle" to="/kitchen">Visão geral</Link><Link className="button subtle" to="/kitchen/assembly">Montagem</Link><button className="button secondary" disabled={authBusy || queue.busy || queue.pending} onClick={() => void end()}>Encerrar turno</button></div></header>
    <div className="oven-toolbar"><span>Forno {queue.config?.ovenOccupancy ?? oven.inside.length}{queue.config?.ovenCapacity ? ` / ${queue.config.ovenCapacity} · capacidade indicativa` : ''}</span><button className="button secondary" disabled={queue.refreshing || queue.busy} onClick={queue.reload}>Atualizar</button><button className="button subtle" aria-pressed={session.available} disabled={authBusy || queue.busy || queue.pending} onClick={() => void setAvailability(!session.available)}>{session.available ? 'Suspender recebimento de montagem' : 'Retomar recebimento de montagem'}</button></div>
    {(queue.error || authError) && <p className="oven-alert" role="alert">{queue.error} {authError}</p>}{queue.notice && <p role="status" className="oven-notice">{queue.notice}</p>}{queue.pending && <button className="button secondary" disabled={queue.busy || queue.connection !== 'ONLINE'} onClick={queue.retry}>Confirmar envio</button>}{queue.loading && <p role="status">Carregando produção…</p>}
    <div className="oven-columns"><section className="oven-column"><h2>No forno <span>{oven.inside.length}</span></h2><div className="oven-cards">{oven.inside.map(({ order, pizza }) => { const timing = ovenTiming(pizza, serverNow); return <article className={`oven-card oven-time-${timing.phase.toLowerCase()}`} data-pizza-id={pizza.id} key={pizza.id}><div className="oven-card-heading"><strong>#{order.number} · Pizza {pizza.position + 1}</strong><span className="oven-size">{pizza.snapshot.size === 'BROTO' ? 'Broto' : 'Grande'}</span></div><h3>{ovenFlavor(pizza)}</h3><p>{pizza.snapshot.composition === 'HALF_HALF' ? 'Meio a meio' : 'Inteira'} · {pizza.snapshot.crust.name}</p><div className="oven-clock"><strong>{formatDuration(timing.elapsed)}</strong><span>{timing.duration ? `Previsto ${formatDuration(timing.duration)}` : 'Sem previsão histórica'} · {({ NORMAL: 'No tempo', NEAR: 'Próxima da saída', REACHED: 'Tempo previsto atingido', OVER: 'Tempo excedido' })[timing.phase]}</span></div>{pizza.snapshot.notes && <p className="oven-notes">{pizza.snapshot.notes}</p>}<button className="button primary" disabled={!enabled} onClick={() => queue.command(`/orders/v2/${order.id}/pizzas/${pizza.id}/commands`, { command: 'REMOVE_FROM_OVEN', expectedState: pizza.production.state, expectedVersion: pizza.production.version })}>Retirar do forno</button></article>; })}{!oven.inside.length && <p className="oven-empty">Nenhuma pizza no forno</p>}</div>
      {oven.waiting.length > 0 && <section><h3>Fila anterior · aguardando entrada</h3>{oven.waiting.map(({ order, pizza }) => <article className="oven-card" key={pizza.id}><strong>#{order.number} · Pizza {pizza.position + 1}</strong><p>{ovenFlavor(pizza)}</p><button className="button secondary" disabled={!enabled} onClick={() => queue.command(`/orders/v2/${order.id}/pizzas/${pizza.id}/commands`, { command: 'ENTER_OVEN', expectedState: 'WAITING_OVEN', expectedVersion: pizza.production.version })}>Colocar no forno</button></article>)}</section>}
    </section><section className="oven-column"><h2>Acabamento <span>{finishing.length}</span></h2><div className="oven-cards">{finishing.map(({ order, pizza }) => <article className="oven-card finishing-item" data-pizza-id={pizza.id} key={pizza.id}><strong>#{order.number} · Pizza {pizza.position + 1}</strong><h3>{ovenFlavor(pizza)}</h3><p>{pizza.snapshot.size === 'BROTO' ? 'Broto' : 'Grande'} · saída há {formatDuration(elapsedSeconds(pizza.production.bakedAt!, serverNow))}</p>{pizza.snapshot.notes && <p className="oven-notes">{pizza.snapshot.notes}</p>}<button className="button primary" disabled={!enabled} onClick={() => queue.command(`/orders/v2/${order.id}/pizzas/${pizza.id}/commands`, { command: 'FINISH_PIZZA', expectedState: pizza.production.state, expectedVersion: pizza.production.version })}>Finalizar pizza</button></article>)}{!finishing.length && <p className="oven-empty">Nenhuma pizza em acabamento</p>}</div></section></div>
    <RouteStaging routes={queue.routes} orders={queue.orders} command={queue.command} enabled={enabled} />
  </section>;
}
