import { useState } from 'react';
import type { DispatchRouteView, Order, PizzaItem } from '@guigs/shared';
import { ovenFlavor } from '../oven/oven';
import { channelLabel, fulfillmentLabel } from './OrderContext';

type Command = (path: string, body: Record<string, unknown>) => void;
type Props = { routes: DispatchRouteView[]; orders: Order[]; enabled: boolean; command: Command; counter?: boolean; dock?: boolean; now?: number; selectedRouteId?: string; embedded?: boolean };
export function RouteStaging({ routes, orders, enabled, command, counter = false, dock = false, selectedRouteId, embedded = false }: Props) {
  const [selected, setSelected] = useState(''), [target, setTarget] = useState(''), [open, setOpen] = useState(!dock);
  const visible = routes.filter(value => counter || value.status !== 'DISPATCHED');
  const route = routes.find(value => value.id === (selectedRouteId ?? selected)) ?? visible.find(value => value.status === 'OPEN') ?? visible[0];
  const all = orders.flatMap(order => order.items.filter((item): item is PizzaItem => item.kind === 'PIZZA').map(pizza => ({ order, pizza })));
  const assigned = new Set(routes.flatMap(value => value.items.map(item => item.pizzaId)));
  const available = all.filter(({ pizza }) => pizza.production.state === 'FINISHED' && !assigned.has(pizza.id));
  const act = (body: Record<string, unknown>) => { if (route) command(`/dispatch/routes/${route.id}/commands`, { expectedVersion: route.version, ...body }); };
  const context = (order: Order) => <small>{order.customerName} · {fulfillmentLabel(order)} · {channelLabel(order.channel)}</small>;
  return <section className={`flow-routes${dock ? ' flow-route-dock' : ''}${embedded ? ' flow-route-editor' : ''}`}>
    {!embedded && <header className="flow-section-heading"><h2>Rotas <small>{available.length} pizzas disponíveis</small></h2><div className="flow-dock-actions"><button className="button secondary" disabled={!enabled} onClick={() => { setOpen(true); setSelected(''); command('/dispatch/routes/commands', { command: 'CREATE' }); }}>Criar rota</button>{dock && <button className="button subtle" aria-expanded={open} onClick={() => setOpen(value => !value)}>{open ? 'Recolher organização' : 'Organizar rotas'}</button>}</div></header>}
    {!embedded && <div className="flow-route-tabs" aria-label="Selecionar rota">{visible.map(value => <button key={value.id} className="button subtle" aria-pressed={route?.id === value.id} onClick={() => { setSelected(value.id); setOpen(true); }}>Rota {String(value.routeNumber).padStart(2, '0')} · {value.status === 'OPEN' ? 'Aberta' : value.status === 'CLOSED' ? 'Fechada' : 'Saiu'}</button>)}</div>}
    {open && (route ? <div className="flow-route-columns">
      <section><h3>Finalizadas sem rota</h3><div className="flow-scroll" tabIndex={0} aria-label="Pizzas disponíveis para rota">{available.map(({ order, pizza }) => <div className="flow-route-item" key={pizza.id}><span><strong>#{order.number} · Pizza {pizza.position + 1}</strong>{context(order)}<small>{ovenFlavor(pizza)}</small></span><button className="button secondary" disabled={!enabled || route.status !== 'OPEN'} onClick={() => act({ command: 'ADD', pizzaId: pizza.id })}>Adicionar</button></div>)}{!available.length && <p className="oven-empty">Nenhuma pizza disponível</p>}</div></section>
      <section aria-label={`Composição da rota ${route.routeNumber}`}><h3>Rota {String(route.routeNumber).padStart(2, '0')} · {new Set(route.items.map(item => item.orderId)).size} pedidos · {route.items.length} pizzas</h3>
        <div className="flow-scroll" tabIndex={0} aria-label="Pizzas na rota">{route.items.map(item => { const entry = all.find(({ pizza }) => pizza.id === item.pizzaId); return <div key={item.pizzaId} className="flow-route-item"><span>{entry ? <><strong>#{entry.order.number} · Pizza {entry.pizza.position + 1}</strong>{context(entry.order)}<small>{ovenFlavor(entry.pizza)}</small></> : <strong>Pizza de pedido concluído · histórico preservado</strong>}</span>{route.status === 'OPEN' && <div><button className="button subtle" disabled={!enabled} onClick={() => act({ command: 'REMOVE', pizzaId: item.pizzaId })}>Remover</button>{counter && <button className="button subtle" disabled={!enabled || !routes.some(value => value.id === target && value.status === 'OPEN' && value.id !== route.id)} onClick={() => { const destination = routes.find(value => value.id === target); if (destination) act({ command: 'MOVE', pizzaId: item.pizzaId, targetRouteId: target, targetExpectedVersion: destination.version }); }}>Mover</button>}</div>}</div>; })}
          {[...new Set(route.items.map(item => item.orderId))].map(id => { const order = orders.find(value => value.id === id); if (!order) return null; const pizzas = order.items.filter(item => item.kind === 'PIZZA' && item.production.state !== 'CANCELLED'), included = route.items.filter(item => item.orderId === id).length; return <p key={id} className={included < pizzas.length ? 'flow-pending' : ''}>#{order.number}: {included}/{pizzas.length} pizzas nesta rota{included < pizzas.length ? ' · Pedido incompleto' : ''}</p>; })}
        </div>
        <div className="flow-route-footer">{counter && route.status === 'OPEN' && <label>Mover para<select value={target} onChange={event => setTarget(event.target.value)}><option value="">Outra rota aberta</option>{routes.filter(value => value.id !== route.id && value.status === 'OPEN').map(value => <option key={value.id} value={value.id}>Rota {value.routeNumber}</option>)}</select></label>}{route.status === 'OPEN' && <button className="button primary" disabled={!enabled || !route.items.length} onClick={() => act({ command: 'CLOSE' })}>Fechar rota</button>}{counter && route.status === 'CLOSED' && <button className="button secondary" disabled={!enabled} onClick={() => act({ command: 'REOPEN' })}>Reabrir rota</button>}{route.status === 'DISPATCHED' && <strong>Saída registrada · composição encerrada</strong>}</div>
      </section>
    </div> : <p className="oven-empty">Crie uma rota para organizar as pizzas finalizadas.</p>)}
  </section>;
}
