import { useState } from 'react';
import type { DispatchRouteView, Order, PizzaItem } from '@guigs/shared';
import { ovenFlavor } from '../oven/oven';
type Command = (path: string, body: Record<string, unknown>) => void;
export function RouteStaging({ routes, orders, enabled, command, counter = false }: { routes: DispatchRouteView[]; orders: Order[]; enabled: boolean; command: Command; counter?: boolean }) {
  const [selected, setSelected] = useState<string>(''), [target, setTarget] = useState<string>('');
  const route = routes.find(value => value.id === selected) ?? routes.find(value => value.status !== 'DISPATCHED');
  const all = orders.flatMap(order => order.items.filter((item): item is PizzaItem => item.kind === 'PIZZA').map(pizza => ({ order, pizza })));
  const assigned = new Set(routes.flatMap(value => value.items.map(item => item.pizzaId))), available = all.filter(({ pizza }) => pizza.production.state === 'FINISHED' && !assigned.has(pizza.id));
  const act = (body: Record<string, unknown>) => { if (route) command(`/dispatch/routes/${route.id}/commands`, { expectedVersion: route.version, ...body }); };
  return <section className="flow-routes"><header className="flow-section-heading"><h2>Rotas</h2><button className="button secondary" disabled={!enabled} onClick={() => command('/dispatch/routes/commands', { command: 'CREATE' })}>Criar rota</button></header>
    <div className="flow-route-tabs">{routes.filter(value => counter || value.status !== 'DISPATCHED').map(value => <button key={value.id} className="button subtle" aria-pressed={route?.id === value.id} onClick={() => setSelected(value.id)}>Rota {String(value.routeNumber).padStart(2, '0')} · {value.status === 'OPEN' ? 'Aberta' : value.status === 'CLOSED' ? 'Fechada' : 'Saiu'}</button>)}</div>
    {route ? <div className="flow-route-columns"><section><h3>Finalizadas sem rota</h3>{available.map(({ order, pizza }) => <div className="flow-route-item" key={pizza.id}><span>#{order.number} · Pizza {pizza.position + 1}<small>{ovenFlavor(pizza)}</small></span><button className="button secondary" disabled={!enabled || route.status !== 'OPEN'} onClick={() => act({ command: 'ADD', pizzaId: pizza.id })}>Adicionar</button></div>)}{!available.length && <p className="oven-empty">Nenhuma pizza disponível</p>}</section><section aria-label={`Composição da rota ${route.routeNumber}`}><h3>Rota {String(route.routeNumber).padStart(2, '0')} · {route.items.length} pizzas</h3>{route.items.map(item => { const entry = all.find(({ pizza }) => pizza.id === item.pizzaId); return <div key={item.pizzaId} className="flow-route-item"><span>#{entry?.order.number ?? 'Pedido concluído'} · Pizza {(entry?.pizza.position ?? 0) + 1}<small>{entry ? ovenFlavor(entry.pizza) : 'Composição preservada no histórico'}</small></span>{route.status === 'OPEN' && <div><button className="button subtle" disabled={!enabled} onClick={() => act({ command: 'REMOVE', pizzaId: item.pizzaId })}>Remover</button>{counter && <button className="button subtle" disabled={!enabled || !target} onClick={() => { const destination = routes.find(value => value.id === target); if (destination) act({ command: 'MOVE', pizzaId: item.pizzaId, targetRouteId: target, targetExpectedVersion: destination.version }); }}>Mover</button>}</div>}</div>; })}
      {[...new Set(route.items.map(item => item.orderId))].map(id => { const order = orders.find(value => value.id === id); if (!order) return null; const pizzas = order.items.filter(item => item.kind === 'PIZZA' && item.production.state !== 'CANCELLED'); const included = route.items.filter(item => item.orderId === id).length; return <p key={id} className={included < pizzas.length || pizzas.some(pizza => pizza.kind === 'PIZZA' && pizza.production.state !== 'FINISHED') ? 'flow-pending' : ''}>#{order.number}: {included}/{pizzas.length} pizzas nesta rota{included < pizzas.length ? ' · Pedido incompleto' : ''}</p>; })}
      {counter && route.status === 'OPEN' && <label>Mover para<select value={target} onChange={event => setTarget(event.target.value)}><option value="">Selecione outra rota aberta</option>{routes.filter(value => value.id !== route.id && value.status === 'OPEN').map(value => <option key={value.id} value={value.id}>Rota {value.routeNumber}</option>)}</select></label>}
      {route.status === 'OPEN' && <button className="button primary" disabled={!enabled || !route.items.length} onClick={() => act({ command: 'CLOSE' })}>Fechar rota</button>}{counter && route.status === 'CLOSED' && <button className="button secondary" disabled={!enabled} onClick={() => act({ command: 'REOPEN' })}>Reabrir rota</button>}{route.status === 'DISPATCHED' && <strong>Saída registrada · composição encerrada</strong>}
    </section></div> : <p className="oven-empty">Nenhuma rota aberta</p>}
  </section>;
}
