import { OperationalNavigation } from '../../components/OperationalNavigation';
import type { Order, OperationalSession, DispatchRouteView } from '@guigs/shared';
import { useOperatorSession } from '../kitchen/useOperatorSession';
import { OperatorPin } from '../kitchen/components/OperatorPin';
import { AssemblyIcon } from '../kitchen/components/AssemblyIcons';
import { useOperationalFlow } from '../kitchen/useOperationalFlow';
import { RouteStaging } from '../kitchen/RouteStaging';
import type { SessionCredentials } from '../kitchen/operatorSession';
import { PhysicalPizzaSummary } from './PhysicalPizzaSummary';
import '../kitchen/assembly.css';
import '../oven/oven.css';
import '../finishing/finishing.css';
import '../kitchen/operational-flow.css';
type Command = (path: string, body: Record<string, unknown>) => void;
export function CounterDispatchPage() { const auth = useOperatorSession(); if (!auth.session || !auth.credentials) return <OperatorPin {...auth} module="Balcão · Despacho" />; return <Counter key={auth.session.sessionId} session={auth.session} credentials={auth.credentials} authBusy={auth.busy} authError={auth.error} end={auth.end} />; }
function Counter({ session, credentials, authBusy, authError, end }: { session: OperationalSession; credentials: SessionCredentials; authBusy: boolean; authError: string; end: () => Promise<void> }) {
  const queue = useOperationalFlow(credentials, session.sessionId), enabled = queue.canAct && !authBusy && !authError && session.presenceStatus === 'ONLINE';
  return <section className="oven-page counter-dispatch"><header className="oven-header"><div><h1><AssemblyIcon name="flag" />Balcão · Despacho</h1><p aria-label="Identidade operacional">{session.operatorName} · {session.workstationName}</p></div><div className="oven-header-actions"><span role="status">{queue.connection === 'ONLINE' ? 'Online' : queue.connection === 'OFFLINE' ? 'Offline' : 'Reconectando'}</span><OperationalNavigation /><button className="button secondary" disabled={authBusy || queue.busy || queue.pending} onClick={() => void end()}>Encerrar turno</button></div></header>
    <div className="oven-toolbar"><button className="button secondary" disabled={queue.refreshing || queue.busy} onClick={queue.reload}>Atualizar</button><span className="station-policy">Recebimento de montagem exclusivo à estação Montagem</span></div>
    {(queue.error || authError) && <p role="alert" className="oven-alert">{queue.error} {authError}</p>}{queue.notice && <p role="status" className="oven-notice">{queue.notice}</p>}{queue.pending && <button className="button secondary" disabled={queue.busy || queue.connection !== 'ONLINE'} onClick={queue.retry}>Confirmar envio</button>}{queue.loading && <p role="status">Carregando rotas…</p>}
    <h2>Rotas fechadas para conferência</h2>{queue.routes.filter(route => route.status === 'CLOSED').map(route => <ClosedRoute key={route.id} route={route} orders={queue.orders} command={queue.command} enabled={enabled} />)}{!queue.routes.some(route => route.status === 'CLOSED') && <p className="oven-empty">Nenhuma rota fechada</p>}
    <RouteStaging routes={queue.routes} orders={queue.orders} command={queue.command} enabled={enabled} counter />
    <h2>Saídas em andamento</h2><div className="flow-counter-orders">{queue.orders.filter(order => ['OUT_FOR_DELIVERY', 'READY_FOR_PICKUP'].includes(order.status)).map(order => <article className="flow-counter-order" key={order.id}><h3>#{order.number} · {order.customerName}</h3><p>{order.status === 'OUT_FOR_DELIVERY' ? 'Em rota' : 'Pronto para retirada'}</p><button className="button primary" disabled={!enabled} onClick={() => queue.command(`/orders/v2/${order.id}/dispatch/commands`, { command: order.status === 'OUT_FOR_DELIVERY' ? 'MARK_DELIVERED' : 'MARK_PICKED_UP', expectedVersion: order.version })}>{order.status === 'OUT_FOR_DELIVERY' ? 'Confirmar entrega' : 'Confirmar retirada'}</button></article>)}</div>
    {queue.orders.some(order => order.operationalFlowVersion !== 2 && ['WAITING_DISPATCH', 'WAITING_DRIVER'].includes(order.status)) && <section><h2>Pedidos anteriores sem rota</h2>{queue.orders.filter(order => order.operationalFlowVersion !== 2 && ['WAITING_DISPATCH', 'WAITING_DRIVER'].includes(order.status)).map(order => <article className="flow-counter-order" key={order.id}><h3>#{order.number} · {order.customerName}</h3><button className="button secondary" disabled={!enabled} onClick={() => queue.command(`/orders/v2/${order.id}/dispatch/commands`, { command: order.fulfillmentType === 'PICKUP' ? 'MARK_READY_FOR_PICKUP' : order.status === 'WAITING_DISPATCH' ? 'MARK_WAITING_DRIVER' : 'MARK_OUT_FOR_DELIVERY', expectedVersion: order.version })}>{order.fulfillmentType === 'PICKUP' ? 'Preparar retirada' : order.status === 'WAITING_DISPATCH' ? 'Aguardar entregador' : 'Registrar saída'}</button></article>)}</section>}
  </section>;
}
function ClosedRoute({ route, orders, enabled, command }: { route: DispatchRouteView; orders: Order[]; enabled: boolean; command: Command }) {
  const involved = orders.filter(order => route.items.some(item => item.orderId === order.id));
  const complete = involved.length > 0 && involved.every(order => order.status === 'WAITING_DISPATCH' && order.items.filter(item => item.kind === 'PIZZA' && item.production.state !== 'CANCELLED').every(item => route.items.some(link => link.pizzaId === item.id)));
  return <section className="flow-routes" aria-label={`Rota fechada ${route.routeNumber}`}><header className="flow-section-heading"><h2>Rota {String(route.routeNumber).padStart(2, '0')}</h2><span>{involved.length} pedidos · {route.items.length} pizzas</span></header><div className="flow-counter-orders">{involved.map(order => <Conference key={order.id} order={order} route={route} enabled={enabled} command={command} />)}</div><div className="flow-counter-actions"><button className="button primary" disabled={!enabled || !complete} onClick={() => { if (window.confirm('Registrar saída desta rota? A composição será encerrada.')) command(`/dispatch/routes/${route.id}/commands`, { command: 'DISPATCH', expectedVersion: route.version }); }}>Registrar saída da rota</button><button className="button secondary" disabled={!enabled} onClick={() => command(`/dispatch/routes/${route.id}/commands`, { command: 'REOPEN', expectedVersion: route.version })}>Reabrir rota</button>{!complete && <p className="flow-pending">Confira todos os pedidos, pizzas, extras e embalagem. Pedidos parciais não podem sair.</p>}</div></section>;
}
function Conference({ order, route, enabled, command }: { order: Order; route: DispatchRouteView; enabled: boolean; command: Command }) {
  const act = (body: Record<string, unknown>) => command(`/counter/orders/${order.id}/conference/commands`, { expectedVersion: order.version, ...body });
  const pizzas = order.items.filter(item => item.kind === 'PIZZA' && item.production.state !== 'CANCELLED'), extras = order.items.filter(item => item.kind === 'EXTRA' && item.state !== 'CANCELLED');
  const all = pizzas.every(pizza => pizza.kind === 'PIZZA' && pizza.production.state === 'FINISHED' && Boolean(pizza.counterCheckedAt || order.operationalFlowVersion !== 2) && route.items.some(item => item.pizzaId === pizza.id)) && extras.every(extra => extra.kind === 'EXTRA' && extra.checkedQuantity === extra.quantity);
  const mutable = enabled && !['WAITING_DRIVER', 'OUT_FOR_DELIVERY', 'READY_FOR_PICKUP', 'DELIVERED', 'PICKED_UP'].includes(order.status);
  return <article className="flow-counter-order" data-order-id={order.id}><h3>#{order.number} · {order.customerName}</h3><p>{order.fulfillmentType === 'DELIVERY' ? 'Delivery' : 'Retirada'} · {pizzas.length} pizzas</p>{pizzas.map(pizza => pizza.kind === 'PIZZA' && <div className="flow-counter-line" key={pizza.id}><PhysicalPizzaSummary pizza={pizza} /><span>{pizza.production.state !== 'FINISHED' ? 'Produção pendente' : !route.items.some(item => item.pizzaId === pizza.id) ? 'Fora desta rota' : pizza.counterCheckedAt || order.operationalFlowVersion !== 2 ? 'Conferida no Balcão' : 'A conferir'}</span>{pizza.production.state === 'FINISHED' && order.operationalFlowVersion === 2 && route.items.some(item => item.pizzaId === pizza.id) && <button className="button secondary" disabled={!mutable} onClick={() => { if (!pizza.counterCheckedAt || window.confirm('Desfazer a conferência desta pizza e embalagem?')) act({ command: pizza.counterCheckedAt ? 'UNCHECK_PIZZA' : 'CHECK_PIZZA', pizzaId: pizza.id, expectedItemVersion: pizza.production.version }); }}>{pizza.counterCheckedAt ? 'Corrigir conferência' : 'Conferir pizza'}</button>}</div>)}
    <h4>Extras e bebidas</h4>{extras.map(extra => extra.kind === 'EXTRA' && <div className="flow-counter-line" key={extra.id}><strong>{extra.snapshot.name} · {extra.checkedQuantity}/{extra.quantity}</strong>{extra.checkedQuantity < extra.quantity && <button className="button secondary" disabled={!mutable} onClick={() => act({ command: 'CHECK_EXTRA', extraId: extra.id, expectedItemVersion: extra.version, checkedQuantity: extra.checkedQuantity + 1 })}>Conferir 1 unidade</button>}{extra.checkedQuantity > 0 && <button className="button subtle" disabled={!mutable} onClick={() => { if (window.confirm('Reduzir conferência e invalidar embalagem?')) act({ command: 'UNCHECK_EXTRA', extraId: extra.id, expectedItemVersion: extra.version, checkedQuantity: extra.checkedQuantity - 1 }); }}>Corrigir extra</button>}</div>)}{!extras.length && <p className="flow-counter-notice">Sem extras</p>}
    <button className="button secondary" disabled={!mutable || (!order.packingFinishedAt && !all)} onClick={() => { if (!order.packingFinishedAt || window.confirm('Desfazer conferência da embalagem?')) act({ command: order.packingFinishedAt ? 'UNCONFIRM_PACKAGING' : 'CONFIRM_PACKAGING' }); }}>{order.packingFinishedAt ? 'Corrigir embalagem' : 'Conferir embalagem'}</button>
    {order.status !== 'WAITING_DISPATCH' ? <button className="button primary" disabled={!mutable || !all || !order.packingFinishedAt} onClick={() => act({ command: 'RELEASE_TO_DISPATCH' })}>Pedido pronto para saída</button> : <strong>Pedido conferido · pronto para saída</strong>}{order.notes && <p className="oven-notes">{order.notes}</p>}
  </article>;
}
